
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuvvezmucfeaswkmerbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dnZlem11Y2ZlYXN3a21lcmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDE1NjgsImV4cCI6MjA1OTcxNzU2OH0.UZ26z9EUhlSt9nZRm5aCJGsb_zVhWo_-8VHaK4Xpjj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
